/* 
 * Forge Design Automation
 *
 * Generated by [Forge Swagger Codegen](https://git.autodesk.com/forge-ozone/forge-rsdk-codegen)
 */

using System;
using System.Reflection;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Net.Http;

namespace Autodesk.Forge.DesignAutomation
{
    /// <summary>
    /// Represents a set of configuration settings
    /// </summary>
    public class Configuration
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Configuration" /> class
        /// </summary>
        public Configuration()
        {
            this.BaseAddress = new Uri("https://developer.api.autodesk.com/da/us-east/");
        }

        /// <summary>
        /// Gets or sets the base path for API access.
        /// </summary>
        public Uri BaseAddress { get; set;}
    }
}
