/* 
 * Forge Design Automation
 *
 * Generated by [Forge Swagger Codegen](https://git.autodesk.com/design-automation/forge-rsdk-codegen)
 */

using Autodesk.Forge.Core;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Autodesk.Forge.DesignAutomation.Http;

namespace Autodesk.Forge.DesignAutomation
{
    public static class ServiceCollectionExtensions
    {
        public static IServiceCollection ConfigureDesignAutomation(this IServiceCollection services, IConfiguration configuration)
        {
            services.ConfigureForge(configuration);
            return services.Configure<Configuration>(configuration.GetSection("Forge").GetSection("DesignAutomation"));
        }
        public static IServiceCollection AddDesignAutomation(this IServiceCollection services)
        {
            services.AddForgeService();
            services.AddTransient<IActivitiesApi,ActivitiesApi>();
            services.AddTransient<IActivitiesApiHttp,ActivitiesApiHttp>();
            services.AddTransient<IAppBundlesApi,AppBundlesApi>();
            services.AddTransient<IAppBundlesApiHttp,AppBundlesApiHttp>();
            services.AddTransient<IEnginesApi,EnginesApi>();
            services.AddTransient<IEnginesApiHttp,EnginesApiHttp>();
            services.AddTransient<IForgeAppsApi,ForgeAppsApi>();
            services.AddTransient<IForgeAppsApiHttp,ForgeAppsApiHttp>();
            services.AddTransient<IHealthApi,HealthApi>();
            services.AddTransient<IHealthApiHttp,HealthApiHttp>();
            services.AddTransient<ISharesApi,SharesApi>();
            services.AddTransient<ISharesApiHttp,SharesApiHttp>();
            services.AddTransient<IWorkItemsApi,WorkItemsApi>();
            services.AddTransient<IWorkItemsApiHttp,WorkItemsApiHttp>();
            return services;
        }
    }
}
