/* 
 * Forge Design Automation
 *
 * Generated by [Forge Swagger Codegen](https://git.autodesk.com/design-automation/forge-rsdk-codegen)
 */

using Autodesk.Forge.Core;
using Microsoft.Extensions.Options;
using System.Net.Http;
using Autodesk.Forge.DesignAutomation.Http;
using Autodesk.Forge.DesignAutomation.Model;

namespace Autodesk.Forge.DesignAutomation
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISharesApi
    {
        /// <summary>
        /// Gets all Shares (AppBundles and Activities) shared by this Forge app.
        /// </summary>
        /// <remarks>
        /// Gets all Shares (AppBundles and Activities) shared by this Forge app (shared to other  Forge apps for them to use).                Sharing of AppBundles and Activities is controlled via the use of &#39;aliases&#39;.
        /// </remarks>
        /// <exception cref="HttpRequestException">Thrown when fails to make API call</exception>
        /// <param name="page">Used to get subsequent &#39;pages&#39; of data. (optional)</param>
        /// <returns>Task of PageShares</returns>
        System.Threading.Tasks.Task<PageShares> GetSharesAsync (string page = null);
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SharesApi : ISharesApi
    {
        public readonly SharesApiHttp LowLevelApi;

        /// <summary>
        /// Initializes a new instance of the <see cref="SharesApi"/> class
        /// using ForgeService object
        /// </summary>
        /// <param name="service">An instance of ForgeService</param>
        /// <returns></returns>
        public SharesApi(ForgeService service = null, IOptions<Configuration> configuration = null)
        {
            this.LowLevelApi = new SharesApiHttp(service);
        }

        /// <summary>
        /// Gets all Shares (AppBundles and Activities) shared by this Forge app. Gets all Shares (AppBundles and Activities) shared by this Forge app (shared to other  Forge apps for them to use).                Sharing of AppBundles and Activities is controlled via the use of &#39;aliases&#39;.
        /// </summary>
        /// <exception cref="HttpRequestException">Thrown when fails to make API call</exception>
        /// <param name="page">Used to get subsequent &#39;pages&#39; of data. (optional)</param>
        /// <returns>Task of PageShares</returns>
        public async System.Threading.Tasks.Task<PageShares> GetSharesAsync (string page = null)
        {
             var localVarResponse = await this.LowLevelApi.GetSharesAsync(page);
             return localVarResponse.Content;

        }
    }
}
