/* 
 * Forge Design Automation
 *
 * Generated by [Forge Swagger Codegen](https://git.autodesk.com/design-automation/forge-rsdk-codegen)
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Autodesk.Forge.DesignAutomation.Model
{
    /// <summary>
    /// BadRequestObjectResult
    /// </summary>
    [DataContract]
    public partial class BadRequestObjectResult 
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BadRequestObjectResult" /> class.
        /// </summary>
        public BadRequestObjectResult()
        {
        }
        
        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name="value", EmitDefaultValue=false)]
        public Object Value { get; set; }

        /// <summary>
        /// Gets or Sets Formatters
        /// </summary>
        [DataMember(Name="formatters", EmitDefaultValue=false)]
        public List<string> Formatters { get; set; }

        /// <summary>
        /// Gets or Sets ContentTypes
        /// </summary>
        [DataMember(Name="contentTypes", EmitDefaultValue=false)]
        public List<string> ContentTypes { get; set; }

        /// <summary>
        /// Gets or Sets DeclaredType
        /// </summary>
        [DataMember(Name="declaredType", EmitDefaultValue=false)]
        public string DeclaredType { get; set; }

        /// <summary>
        /// Gets or Sets StatusCode
        /// </summary>
        [DataMember(Name="statusCode", EmitDefaultValue=false)]
        public int StatusCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }

}
