/* 
 * Forge Design Automation
 *
 * Generated by [Forge Swagger Codegen](https://git.autodesk.com/design-automation/forge-rsdk-codegen)
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Autodesk.Forge.DesignAutomation.Model
{
    /// <summary>
    /// ( response only ).
    /// </summary>
    [DataContract]
    public partial class NicknameRecord 
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NicknameRecord" /> class.
        /// </summary>
        /// <param name="Nickname">Nickname.</param>
        /// <param name="PublicKey">PublicKey.</param>
        public NicknameRecord(string Nickname = default(string), PublicKey PublicKey = default(PublicKey))
        {
            this.Nickname = Nickname;
            this.PublicKey = PublicKey;
        }
        
        /// <summary>
        /// Gets or Sets Nickname
        /// </summary>
        [DataMember(Name="nickname", EmitDefaultValue=false)]
        public string Nickname { get; set; }

        /// <summary>
        /// Gets or Sets PublicKey
        /// </summary>
        [DataMember(Name="publicKey", EmitDefaultValue=false)]
        public PublicKey PublicKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }

}
