/* 
 * Forge SDK
 *
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * Design Automation
 *
 * Generated by [Forge Swagger Codegen](https://git.autodesk.com/forge-ozone/forge-rsdk-codegen)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Autodesk.Forge.DesignAutomation.Model
{
    partial class PublicKey
    {
        public override bool Equals(object obj)
        {
            var other = obj as PublicKey;
            if (other == null)
                return false;
            return this.Exponent.SequenceEqual(other.Exponent) && this.Modulus.SequenceEqual(other.Modulus);
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(Exponent, Modulus);
        }
    }
}
