/* 
 * Forge SDK
 *
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * Design Automation
 *
 * Generated by [Forge Swagger Codegen](https://git.autodesk.com/forge-ozone/forge-rsdk-codegen)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Autodesk.Forge.DesignAutomation.Model
{
    /// <summary>
    /// ( response only ).
    /// </summary>
    [DataContract]
    public partial class Share 
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Share" /> class.
        /// </summary>
        public Share()
        {
        }
        
        /// <summary>
        /// The name alias id with the owner stripped ex: CoolApp+Prod.
        /// </summary>
        /// <value>The name alias id with the owner stripped ex: CoolApp+Prod.</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// The Receiver of the shared alias.
        /// </summary>
        /// <value>The Receiver of the shared alias.</value>
        [DataMember(Name="receiver", EmitDefaultValue=false)]
        public string Receiver { get; set; }

        /// <summary>
        /// The type of the share (\&quot;Activity\&quot;, \&quot;App\&quot;,).
        /// </summary>
        /// <value>The type of the share (\&quot;Activity\&quot;, \&quot;App\&quot;,).</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public ShareType Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }

}
