/* 
 * Forge Design Automation
 *
 * Generated by [Forge Swagger Codegen](https://git.autodesk.com/design-automation/forge-rsdk-codegen)
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Autodesk.Forge.DesignAutomation.Model
{
    /// <summary>
    /// ( response only ).
    /// </summary>
    [DataContract]
    public partial class Shares 
    {
        /// <summary>
        /// The type of the share (\&quot;Activity\&quot;, \&quot;App\&quot;,).
        /// </summary>
        /// <value>The type of the share (\&quot;Activity\&quot;, \&quot;App\&quot;,).</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public ShareType Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Shares" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Shares() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Shares" /> class.
        /// </summary>
        /// <param name="Id">The name alias id with the owner stripped ex: CoolApp+Prod. (required).</param>
        /// <param name="Receiver">The Receiver of the shared alias. (required).</param>
        /// <param name="Type">The type of the share (\&quot;Activity\&quot;, \&quot;App\&quot;,). (required).</param>
        public Shares(string Id = default(string), string Receiver = default(string), ShareType Type = default(ShareType))
        {
            this.Id = Id;
            this.Receiver = Receiver;
            this.Type = Type;
        }
        
        /// <summary>
        /// The name alias id with the owner stripped ex: CoolApp+Prod.
        /// </summary>
        /// <value>The name alias id with the owner stripped ex: CoolApp+Prod.</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// The Receiver of the shared alias.
        /// </summary>
        /// <value>The Receiver of the shared alias.</value>
        [DataMember(Name="receiver", EmitDefaultValue=false)]
        public string Receiver { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }

}
