/* 
 * Forge Design Automation
 *
 * Generated by [Forge Swagger Codegen](https://git.autodesk.com/design-automation/forge-rsdk-codegen)
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Autodesk.Forge.DesignAutomation.Model
{
    /// <summary>
    /// Defines Status
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum Status
    {
        
        /// <summary>
        /// Enum Pending for value: pending
        /// </summary>
        [EnumMember(Value = "pending")]
        Pending = 1,
        
        /// <summary>
        /// Enum Inprogress for value: inprogress
        /// </summary>
        [EnumMember(Value = "inprogress")]
        Inprogress = 2,
        
        /// <summary>
        /// Enum Cancelled for value: cancelled
        /// </summary>
        [EnumMember(Value = "cancelled")]
        Cancelled = 3,
        
        /// <summary>
        /// Enum FailedDownload for value: failedDownload
        /// </summary>
        [EnumMember(Value = "failedDownload")]
        FailedDownload = 4,
        
        /// <summary>
        /// Enum FailedInstructions for value: failedInstructions
        /// </summary>
        [EnumMember(Value = "failedInstructions")]
        FailedInstructions = 5,
        
        /// <summary>
        /// Enum FailedUpload for value: failedUpload
        /// </summary>
        [EnumMember(Value = "failedUpload")]
        FailedUpload = 6,
        
        /// <summary>
        /// Enum FailedLimitProcessingTime for value: failedLimitProcessingTime
        /// </summary>
        [EnumMember(Value = "failedLimitProcessingTime")]
        FailedLimitProcessingTime = 7,
        
        /// <summary>
        /// Enum FailedLimitDataSize for value: failedLimitDataSize
        /// </summary>
        [EnumMember(Value = "failedLimitDataSize")]
        FailedLimitDataSize = 8,
        
        /// <summary>
        /// Enum Success for value: success
        /// </summary>
        [EnumMember(Value = "success")]
        Success = 9
    }

}
