/* 
 * Forge SDK
 *
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * Design Automation
 *
 * Generated by [Forge Swagger Codegen](https://git.autodesk.com/forge-ozone/forge-rsdk-codegen)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Autodesk.Forge.DesignAutomation.Model
{
    /// <summary>
    /// Defines Status
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum Status
    {
        
        /// <summary>
        /// Enum Pending for value: pending
        /// </summary>
        [EnumMember(Value = "pending")]
        Pending = 1,
        
        /// <summary>
        /// Enum Inprogress for value: inprogress
        /// </summary>
        [EnumMember(Value = "inprogress")]
        Inprogress = 2,
        
        /// <summary>
        /// Enum Cancelled for value: cancelled
        /// </summary>
        [EnumMember(Value = "cancelled")]
        Cancelled = 3,
        
        /// <summary>
        /// Enum FailedDownload for value: failedDownload
        /// </summary>
        [EnumMember(Value = "failedDownload")]
        FailedDownload = 4,
        
        /// <summary>
        /// Enum FailedInstructions for value: failedInstructions
        /// </summary>
        [EnumMember(Value = "failedInstructions")]
        FailedInstructions = 5,
        
        /// <summary>
        /// Enum FailedUpload for value: failedUpload
        /// </summary>
        [EnumMember(Value = "failedUpload")]
        FailedUpload = 6,
        
        /// <summary>
        /// Enum FailedLimitProcessingTime for value: failedLimitProcessingTime
        /// </summary>
        [EnumMember(Value = "failedLimitProcessingTime")]
        FailedLimitProcessingTime = 7,
        
        /// <summary>
        /// Enum FailedLimitDataSize for value: failedLimitDataSize
        /// </summary>
        [EnumMember(Value = "failedLimitDataSize")]
        FailedLimitDataSize = 8,
        
        /// <summary>
        /// Enum Success for value: success
        /// </summary>
        [EnumMember(Value = "success")]
        Success = 9
    }

}
