/* 
 * Forge SDK
 *
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * Design Automation
 *
 * Generated by [Forge Swagger Codegen](https://git.autodesk.com/forge-ozone/forge-rsdk-codegen)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Autodesk.Forge.DesignAutomation.Model
{
    /// <summary>
    /// UploadAppBundleParameters
    /// </summary>
    [DataContract]
    public partial class UploadAppBundleParameters 
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UploadAppBundleParameters" /> class.
        /// </summary>
        public UploadAppBundleParameters()
        {
        }
        
        /// <summary>
        /// The URL to upload the AppBundle package to.
        /// </summary>
        /// <value>The URL to upload the AppBundle package to.</value>
        [DataMember(Name="endpointURL", EmitDefaultValue=false)]
        public string EndpointURL { get; set; }

        /// <summary>
        /// FormData parameters to be used in the body of the AppBundle package upload request. Must be followed by a &#39;file&#39; parameter indicating the package file location.
        /// </summary>
        /// <value>FormData parameters to be used in the body of the AppBundle package upload request. Must be followed by a &#39;file&#39; parameter indicating the package file location.</value>
        [DataMember(Name="formData", EmitDefaultValue=false)]
        public Dictionary<string, string> FormData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }

}
