/* 
 * Forge Design Automation
 *
 * Generated by [Forge Swagger Codegen](https://git.autodesk.com/forge-ozone/forge-rsdk-codegen)
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Autodesk.Forge.DesignAutomation.Model
{
    /// <summary>
    /// Defines Verb
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum Verb
    {
        
        /// <summary>
        /// Enum Get for value: get
        /// </summary>
        [EnumMember(Value = "get")]
        Get = 1,
        
        /// <summary>
        /// Enum Head for value: head
        /// </summary>
        [EnumMember(Value = "head")]
        Head = 2,
        
        /// <summary>
        /// Enum Put for value: put
        /// </summary>
        [EnumMember(Value = "put")]
        Put = 3,
        
        /// <summary>
        /// Enum Post for value: post
        /// </summary>
        [EnumMember(Value = "post")]
        Post = 4,
        
        /// <summary>
        /// Enum Patch for value: patch
        /// </summary>
        [EnumMember(Value = "patch")]
        Patch = 5,
        
        /// <summary>
        /// Enum Read for value: read
        /// </summary>
        [EnumMember(Value = "read")]
        Read = 6
    }

}
