/* 
 * Forge SDK
 *
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * Design Automation
 *
 * Generated by [Forge Swagger Codegen](https://git.autodesk.com/forge-ozone/forge-rsdk-codegen)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Autodesk.Forge.DesignAutomation.Model
{
    /// <summary>
    /// Defines Verb
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum Verb
    {
        
        /// <summary>
        /// Enum Get for value: get
        /// </summary>
        [EnumMember(Value = "get")]
        Get = 1,
        
        /// <summary>
        /// Enum Head for value: head
        /// </summary>
        [EnumMember(Value = "head")]
        Head = 2,
        
        /// <summary>
        /// Enum Put for value: put
        /// </summary>
        [EnumMember(Value = "put")]
        Put = 3,
        
        /// <summary>
        /// Enum Post for value: post
        /// </summary>
        [EnumMember(Value = "post")]
        Post = 4,
        
        /// <summary>
        /// Enum Patch for value: patch
        /// </summary>
        [EnumMember(Value = "patch")]
        Patch = 5,
        
        /// <summary>
        /// Enum Read for value: read
        /// </summary>
        [EnumMember(Value = "read")]
        Read = 6
    }

}
