/* 
 * Forge Design Automation
 *
 * Generated by [Forge Swagger Codegen](https://git.autodesk.com/design-automation/forge-rsdk-codegen)
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Autodesk.Forge.DesignAutomation.Model
{
    /// <summary>
    /// WorkItemStatus
    /// </summary>
    [DataContract]
    public partial class WorkItemStatus 
    {
        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public Status Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkItemStatus" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WorkItemStatus() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkItemStatus" /> class.
        /// </summary>
        /// <param name="Status">Status (required).</param>
        /// <param name="Progress">Progress.</param>
        /// <param name="ReportUrl">ReportUrl.</param>
        /// <param name="Stats">Stats.</param>
        /// <param name="Id">Id.</param>
        public WorkItemStatus(Status Status = default(Status), string Progress = default(string), string ReportUrl = default(string), Statistics Stats = default(Statistics), string Id = default(string))
        {
            this.Status = Status;
            this.Progress = Progress;
            this.ReportUrl = ReportUrl;
            this.Stats = Stats;
            this.Id = Id;
        }
        

        /// <summary>
        /// Gets or Sets Progress
        /// </summary>
        [DataMember(Name="progress", EmitDefaultValue=false)]
        public string Progress { get; set; }

        /// <summary>
        /// Gets or Sets ReportUrl
        /// </summary>
        [DataMember(Name="reportUrl", EmitDefaultValue=false)]
        public string ReportUrl { get; set; }

        /// <summary>
        /// Gets or Sets Stats
        /// </summary>
        [DataMember(Name="stats", EmitDefaultValue=false)]
        public Statistics Stats { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }

}
