/* 
 * Forge SDK
 *
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * Design Automation
 *
 * Generated by [Forge Swagger Codegen](https://git.autodesk.com/forge-ozone/forge-rsdk-codegen)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Autodesk.Forge.DesignAutomation.Model
{
    /// <summary>
    /// WorkItemStatus
    /// </summary>
    [DataContract]
    public partial class WorkItemStatus 
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkItemStatus" /> class.
        /// </summary>
        public WorkItemStatus()
        {
        }
        
        /// <summary>
        /// The current status of the workitem.
        /// </summary>
        /// <value>The current status of the workitem.</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public Status Status { get; set; }

        /// <summary>
        /// The current status of the workitem.
        /// </summary>
        /// <value>The current status of the workitem.</value>
        [DataMember(Name="progress", EmitDefaultValue=false)]
        public string Progress { get; set; }

        /// <summary>
        /// The detailed report about the workitem, report url is valid for 24 hours from first receiving it.
        /// </summary>
        /// <value>The detailed report about the workitem, report url is valid for 24 hours from first receiving it.</value>
        [DataMember(Name="reportUrl", EmitDefaultValue=false)]
        public string ReportUrl { get; set; }

        /// <summary>
        /// Basic statistics about workitem processing.
        /// </summary>
        /// <value>Basic statistics about workitem processing.</value>
        [DataMember(Name="stats", EmitDefaultValue=false)]
        public Statistics Stats { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }

}
