/* 
 * Design Automation
 *
 * Generated by [Forge Swagger Codegen](https://git.autodesk.com/forge-ozone/forge-rsdk-codegen)
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Autodesk.Forge.DesignAutomation.Rsdk.Model
{
    /// <summary>
    /// A digitally signed url.
    /// </summary>
    [DataContract]
    public partial class SignedUrl 
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SignedUrl" /> class.
        /// </summary>
        public SignedUrl()
        {
        }
        
        /// <summary>
        /// The Url value.
        /// </summary>
        /// <value>The Url value.</value>
        [DataMember(Name="url", EmitDefaultValue=false)]
        public string Url { get; set; }

        /// <summary>
        /// The signature calculated for Url.
        /// </summary>
        /// <value>The signature calculated for Url.</value>
        [DataMember(Name="signature", EmitDefaultValue=false)]
        public string Signature { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }

}
