version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "monthly"
    default_reviewers:
      - "szilvaa"
      - "augustogoncalves"
      - "zhuliice"
    default_labels:
      - "dependencies"
      - "dependabot"