name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
   
    - name: Build
      run: dotnet build Autodesk.Forge.DesignAutomation.sln /p:UseSharedCompilation=false
   
    - name: Perform CodeQL Analysis
      id: CodeQL_analysis
      uses: github/codeql-action/analyze@v3
    
    - name: Test
      run: dotnet test tests/e2e/E2eTests.csproj
    
    - name: Publish
      if: ${{ github.event_name =='push' && github.ref == 'refs/heads/main' }}
      run: dotnet msbuild src/Autodesk.Forge.DesignAutomation/Autodesk.Forge.DesignAutomation.csproj /t:Push
      env:
        NugetApiKey: ${{ secrets.NUGETAPIKEYBYENGOPS }}
